# Generated by Django 3.0.8 on 2020-08-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='yourname',
            new_name='username',
        ),
    ]
